name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r ml-core/requirements.txt

    - name: Run Python scripts
      run: |
        source .venv/bin/activate
        python -m unittest discover -s ml-core/mlcore -p "*.py"

    - name: Lint Python code
      run: |
        source .venv/bin/activate
        pip install flake8
        flake8 ml-core/mlcore