name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          pip install pytest isort black flake8

      # - name: Run tests
      #   run: |
      #     source .venv/bin/activate
      #     pytest --maxfail=1 --disable-warnings -q

      - name: Lint
        run: |
          source .venv/bin/activate
          isort --check-only mlcore/
          black --check mlcore/
          flake8 --max-line-length=120 --exit-zero mlcore/