name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
        pip install pytest

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --maxfail=1 --disable-warnings -q

    - name: Remove unused code with Autoflake
      run: |
        source .venv/bin/activate
        autoflake \
          --recursive \
          --in-place \
          --remove-unused-variables \
          --remove-all-unused-imports \
          mlcore/
    - name: Check import order with Isort
      run: |
        source .venv/bin/activate
        isort --check-only mlcore/

    - name: Check formatting with Black
      run: |
        source .venv/bin/activate
        black --check mlcore/

    - name: Style and complexity checks with Flake8
      run: |
        source .venv/bin/activate
        flake8 mlcore/

    - name: Static type checks with Mypy
      run: |
        source .venv/bin/activate
        mypy mlcore/